name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
    - uses: actions/checkout@v3
    
    - name: Change to API subdirectory
    - working-directory: ./api

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Go Build
      run: go build -v ./...
      
    - name: Create env file
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
      
    
    - name: Run Go Tests
      run: go test -v ./...
